### ISSUE TITLE
Test suite should test the transmitted JSON report

### ISSUE THREAD

**Issue by tombruijn** [appsignal/diagnose_tests#16]
Testing the output is good, but the real interesting part of the diagnose command line tool is the JSON report it sends to the server. We can implement tests for those in this repository as well, and decide to implement most (*but not all) testing for the diagnose tool in this repository.

\* some internal helper functions/methods may still need to be tested in the integration itself, because it's not possible to create a scenario that tests it in this diagnose_tests test suite.

## TODO

- [x] Decide we want to test the transmitted JSON
- [x] Add a web server that receives the JSON report
- [x] Allow customization of diagnose endpoint in the integrations (using an environment variable?) to point to the local web server
- [x] Fetch and parse the JSON report
- [x] Assert the expectations on the JSON report for every scenario like we do with the CLI output

**Comment by tombruijn** [comment]
Closing this for now. Some improvements have been made testing this, but "Assert the expectations on the JSON report for every scenario like we do with the CLI output" is a little tricky to consider "done".
