### ISSUE TITLE
Add test for output on failed to submit report

### ISSUE THREAD

**Issue by tombruijn** [appsignal/diagnose_tests#32]
When the diagnose server returns a non-200 status code on the `/diag` endpoint, test what the CLI does. The same way we test what happens if people validate the Push API key.

It should print a message about how it failed to send, with the response code and body.

## TODO

- [x] Add response status configuration to mock server
- [ ] Add scenario that tests the CLI output in a non-200 status code
- [ ] Make sure all integrations return a similar error message to explain to the user what went wrong, with additional data (which can differ per integration language) to explain the issue, like the response error object.

**Comment by tombruijn** [comment]
Do we want to CLI to exit with a failure status code in this case?

**Comment by tombruijn** [comment]
> Add response status configuration to mock server

This was added when working on the Push API key validation failure scenario.
